version: '3.9'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/api
    depends_on:
      - db
  db:
    image: bitnami/postgresql:latest
    volumes:
      - $HOME/.postgres/checkmate/data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=checkmate
